### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by patrickgardella** [atiumcache/pure-recipe#19]
I installed the requirements into a venv on my linux system (python 3.12), and when I run pure_recipe.py, I get this error:

```bin/python pure_recipe.py view https://iowagirleats.com/cheesy-taco-soup/
Traceback (most recent call last):
  File "/home/patrick/Documents/projects/pure-recipe/pure_recipe.py", line 331, in <module>
    main()
  File "/home/patrick/Documents/projects/pure-recipe/pure_recipe.py", line 16, in main
    settings = load_yaml()
               ^^^^^^^^^^^
  File "/home/patrick/Documents/projects/pure-recipe/pure_recipe.py", line 292, in load_yaml
    if not os.path.exists(recipe_directory):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

I should note that I get this same error if I run the python script without a command (i.e. "view") or without a URL.

I tried creating the config.yaml, but I get the same error.  And after creating the `recipes` folder.

My first guess is that the os.path is different on Linux than Mac or PC, but I can't be the first person to run this on Linux :)

**Comment by patrickgardella** [comment]
Quick update:

Running this through pdb,  the `settings.get("directory")`   returns `None`. 

I figured out that you were expecting the `config.yaml` file in the `~/.config/pure_recipes` folder, not in the same folder as `pure_recipes.py`. When I moved it there, the script works.

**Comment by gotofritz** [comment]
Yeah I am not sure how that is supposed to work...

```
    if settings is None:
        settings = dict()
        settings["directory"] = None

    recipe_directory = settings.get("directory")
  ```

If settings is None it creates an empty settings and then it loads a nonexistant `recipe_directory` from it. Which obviously leads nowhere. Did this ever work? I suspect the dev just edited the config.yaml in their local env manually and forgot about it
